### ISSUE TITLE
Undefined index: gcm_sender_id in /var/www/site/httpdocs/wp-content/plugins/onesignal-free-web-push-notifications/onesignal-admin.php on line 263

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-WordPress-Plugin#68]
A couple people have reported this issue now (5+).

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-WordPress-Plugin/commit/2cafd7a9463698cb34166af797f8f58b0d77e8eb

**Comment by gigidawg** [comment]
This issue is still happening in Version 1.16.2. Please reopen the issue.
